### PR TITLE
Feature/boostlibfix

### PR DESCRIPTION
**Pull request by nsoblath**
Checks whether Boost libraries were found using the Config method or the Module method in CMake, and links the program_options library into TrackCompare appropriately.

### CODE REVIEW

**Comment by zykure** [comment]
Thanks for the fix, and for pointing out the FindBoost issue. I updated the provided CMake macros in the recent update to v3.7. Could you check if this fixes this issue already? I didn't see any error messages when compiling the code on various systems, including the Docker container.

Also, could you please create a new pull request if the fix is still necessary? This one has 28 commits but only changes a single file.

**Comment by pslocum** [comment]
The Boost libraries are now found using v3.7 , without this pull request.  So I think the request can be closed.

**Comment by nsoblath** [comment]
I'm testing things again now that Kassiopeia 3.7 has been released.  I'll close this PR and make a new one if I find any changes are needed.

**Comment by zykure** [comment]
Thanks, and sorry for the overlap with our new release.

**Pull request closed without merging**
