### PR TITLE
Fix build pipeline & update Docker image

### PR DESCRIPTION
**Pull request by 2xB**
The build pipeline and CI tests are broken since a few hours due to one repository no longer existing for Fedora 37. This commit updates the Docker image & build and CI tests to Fedora 40, also including recent Docker and `kasperenv.sh` updates from KASPER. Most notably, `paraview` and `uproot` are now available inside the full Docker image and running `kasperenv.sh` no longer leads to paths being added multiple times but to paths being replaced correctly.

### CODE REVIEW

**Comment by richeldichel** [comment]
Thanks @2xB. These necessary changes look very good. Can you please edit the documentation as expressed in the test.yaml so that testing and documentation are in sync? Afterwards I would merge.

**Comment by 2xB** [comment]
@richeldichel Sure, what exactly is currently out of sync?

**Comment by 2xB** [comment]
I think that I already covered that documentation update in 81d617309a80ebebc5471019eb88c53366db0c11 .

**Comment by richeldichel** [comment]
I'm blind, apparently. My bad...

**Pull request merged**
